"""Storage ports for the delivery module."""

from __future__ import annotations

from datetime import date
from typing import Protocol

from .entities import Clause, Milestone, Statement, Task


class DeliveryRepository(Protocol):
    def list_milestones(self, project_id: str) -> list[Milestone]: ...

    def list_tasks(self, project_id: str) -> list[Task]: ...

    def get_task(self, task_id: str) -> Task | None: ...

    def find_task_by_code(self, code: str) -> Task | None: ...

    def add_task(self, task: Task) -> Task: ...

    def replace_task(self, task: Task) -> Task: ...

    def get_milestone(self, milestone_id: str) -> Milestone | None: ...

    def replace_milestone(self, milestone: Milestone) -> Milestone: ...

    def list_statements(self, project_id: str) -> list[Statement]: ...

    def get_statement(self, statement_id: str) -> Statement | None: ...

    def list_clauses(self, statement_id: str) -> list[Clause]: ...

    def get_clause(self, clause_id: str) -> Clause | None: ...

    def replace_clause(self, clause: Clause) -> Clause: ...

    def next_task_code(self) -> str: ...

    def tasks_ending_on_or_after(self, project_id: str, boundary: date) -> list[Task]:
        """Tasks a milestone date change would drag along."""
        ...
