"""Ports for the documents module (ADR-018).

``DocumentConverterPort`` is the seam for kordoc, the one integration that already
exists. WP-PKD-030 drops the real adapter in behind this interface; it needs the
converter's install location and call style, which is still an open input.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol

from .entities import Document, DriveFile


class ConversionResult(Protocol):
    @property
    def succeeded(self) -> bool: ...

    @property
    def detail(self) -> str | None: ...


@dataclass(frozen=True, slots=True)
class ConversionArtifact:
    """An immutable conversion output, identified by content, not by caller input.

    ``path`` is generated by the adapter (a UUID-derived filename inside the
    configured, trusted output directory); callers never choose or influence it.
    """

    path: str
    size_bytes: int
    sha256: str


@dataclass(frozen=True, slots=True)
class ArtifactConversionResult:
    """Result of a conversion that also reports the stored artifact.

    ``artifact`` is ``None`` when ``succeeded`` is ``False``.
    """

    succeeded: bool
    detail: str | None
    artifact: ConversionArtifact | None = None


class DocumentConverterPort(Protocol):
    """Turns markdown into hwpx with a form template applied."""

    @property
    def name(self) -> str: ...

    @property
    def version(self) -> str: ...

    def convert(self, markdown: str, *, template: str) -> tuple[bool, str | None]:
        """Return ``(succeeded, failure_detail)``."""
        ...


class ArtifactCapableConverterPort(DocumentConverterPort, Protocol):
    """A converter that also reports the identity of the stored artifact.

    Separate from ``DocumentConverterPort`` so adapters (and fixtures) that
    only implement ``convert`` remain structurally compatible with the base
    port; only adapters that persist a distinct, addressable artifact need
    to implement this one too.
    """

    def convert_with_artifact(
        self, markdown: str, *, template: str
    ) -> ArtifactConversionResult:
        """Like ``convert``, but also returns the stored artifact's identity.

        Each successful call produces a distinct artifact; nothing is
        overwritten. Error details are sanitized categories, never raw
        stdout/stderr, local paths, or markdown content.
        """
        ...


class DocumentRepository(Protocol):
    def list_documents(self, project_id: str) -> list[Document]: ...

    def get_document(self, document_id: str) -> Document | None: ...

    def replace_document(self, document: Document) -> Document: ...

    def list_files(self, project_id: str) -> list[DriveFile]: ...

    def add_file(self, file: DriveFile) -> DriveFile: ...
